baseURL = "http://davidbeck.online/"
languageCode = "en-us"
title = "Blog"
theme = "ananke-f2026-01-12"

SectionPagesMenu = "main"

[params]
  description = "A simple Website for random stuff."
  background_color_class = "bg-gray"
  recent_posts_number = 12
  
  featured_image = "/images/2021/2021-07-23_img_hh.png"
  

[params.ananke.social.follow]
networks = [
  "mastodon"
]

[params.ananke.social.mastodon]
  username = "davidbeck"
  profilelink  = "https://hachyderm.io/@davidbeck"
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true