baseURL = "http://davidbeck.online/"
languageCode = "en-us"
title = "Start"
theme = "ananke"

[params]
  description = "A simple Website for random stuff."
  twitter = "https://twitter.com/davidbeckonline"
  github = "https://github.com/davidbeckonline"
  linkedin = "https://www.linkedin.com/in/david-beck-31442743/"
  background_color_class = "bg-black"
  recent_posts_number = 3
  featured_image = "/images/2021-07-23_img_hh.jpg"