baseURL = "http://davidbeck.online/"
languageCode = "en-us"
title = "Blog"
theme = "ananke"

SectionPagesMenu = "main"

[params]
  description = "A simple Website for random stuff."
  background_color_class = "bg-gray"
  recent_posts_number = 9
  
  featured_image = "/images/2021/2021-07-23_img_hh.png"
  

[params.ananke.social.follow]
networks = [
  "mastodon",
  "codeberg"
]

[params.ananke.social.mastodon]
username = "davidbeck"
profilelink = "https://hachyderm.io/@davidbeck"

[params.ananke.social.networks.codeberg]
slug = "codeberg"
label = "Codeberg"
color = "#2185D0"
profile = "https://codeberg.org/steiger"
icon = "codeberg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true