baseURL = "https://davidbeck.online/"
languageCode = "en-us"
title = "Blog by David Beck"
theme = "ananke"

SectionPagesMenu = "main"

# robot.txt is false because I am not using a template
enableRobotsTXT = false

[params]
  description = "A simple Website for random stuff."
  background_color_class = "bg-gray"
  recent_posts_number = 9
  featured_image = "/images/2021/2021-07-23_img_hh.png"
  
  copyright = "David Beck"

[params.ananke.social.follow]
networks = [
  "mastodon",
  "codeberg",
  "rss"
]

[params.ananke.social.mastodon]
username = "davidbeck"
profilelink = "https://hachyderm.io/@davidbeck"

[params.ananke.social.networks.codeberg]
slug = "codeberg"
label = "Codeberg"
profile = "https://codeberg.org/steiger"
icon = "codeberg"

[params.ananke.social.networks.rss]
slug = "rss"
label = "RSS"
profile = "/index.xml"
icon = "rss"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# RSS Configuration
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[services]
  [services.rss]
    limit = 10